### ISSUE TITLE
Add more user-focused documentation

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers-contrib/cookiecutter-devcontainers-feature#1]
**This issue have "moved" over to https://github.com/jcbhmr/devcontainers-contrib-features/tree/add-cookiecutter-as-subpkg which has this repo included as a sub-pkg on the features repo. These things may not apply anymore.**

---

One of the best ways to get more people to use a thing is to make it easy! I know I have been eyeing adding a `bikeshed` feature (I recently tried my hand at making one based on the [devcontainers/template-starter](https://github.com/devcontainers/template-starter) repo), and I'm sure others are too.

I am happy to involve myself and do some of the grunt work towards making the user documentation better. In fact, that's why I'm opening this issue! When/if you (@danielbraun89) decide to merge my future changes, this can be closed.

Some ideas of things to improve the state of this repository:
- Change the title from "Devcontainers cookie-cutter" to something like "Devcontainer [cookiecutter](https://cookiecutter.readthedocs.io/en/stable/usage.html) template"
- Add a snazzy description like "👨‍🍳 [Cookiecutter](https://cookiecutter.readthedocs.io/en/stable/usage.html)-based feature generator for [devcontainers-contrib/features](https://github.com/devcontainers-contrib/features)"
- Add a header image or GIF like [developit/htm](https://github.com/developit/htm#readme), [asciinema/agg](https://github.com/asciinema/agg#readme), and other projects do (a picture is worth 1000 words)
- Add instructions how to use the project like shown below
- Add more "links" and relationships between this repo and the devcontainers-contrib/features repo. Maybe combine the two? Put this repo as a `git subtree` of that repo? Merge them into a [monorepo](https://semaphoreci.com/blog/what-is-monorepo)? I personally am of the opinion that this should be a subfolder of the main repo _if possible with Cookiecutter_.

See https://github.com/devcontainers-contrib/features/issues/69 on the main devcontainers-contrib/features repo for my additions there too.

---

<details>
  <summary>Add instructions how to use the project</summary>

## Usage

🍪 This project uses [Cookiecutter](https://cookiecutter.readthedocs.io/en/stable/) to generate a folder structure. You can follow their [usage guide](https://cookiecutter.readthedocs.io/en/stable/usage.html) for more details (but generic) instructions.

To add a new feature to the [devcontainers-contrib/features](https://github.com/devcontainers-contrib/features) repository, you should...
1. Read the [`CONTRIBUTING.md`](https://github.com/devcontainers-contrib/features/blob/main/CONTRIBUTING.md)
2. Install Python on your computer following the instructions on [python.org](https://python.org/)
3. Run `pip install cookiecutter` to install Cookiecutter
4. Run `git clone https://github.com/devcontainers-contrib/features.git` to clone the repo
5. _I don't know what to here yet; I haven't actually started tinkering yet as I write this issue..._

</details>

<details>
  <summary>Idea for the README header</summary>

# [devcontainers-contrib/feature]([devcontainers-contrib/features](https://github.com/devcontainers-contrib/features)) new feature template
👨‍🍳 [Cookiecutter](https://cookiecutter.readthedocs.io/en/stable/usage.html)-based source file generator for new [Devcontainer Features](https://containers.dev/implementors/features/)

<div align="center">

![](https://github-readme-stats.vercel.app/api/pin/?username=devcontainers-contrib&repo=features&show_owner=true)

</div>

🤝 Works with devcontainers-contrib/features contributing process \
🍪 Easy to use with Python and Cookiecutter

## Installation

![PyPI](https://img.shields.io/static/v1?style=for-the-badge&message=PyPI&color=3775A9&logo=PyPI&logoColor=FFFFFF&label=)

You will need to [install Cookiecutter](https://cookiecutter.readthedocs.io/en/stable/installation.html) for this project to work.

```bash
pip install cookiecutter
```

## Usage

![Python](https://img.shields.io/static/v1?style=for-the-badge&message=Python&color=3776AB&logo=Python&logoColor=FFFFFF&label=)
![Cookiecutter](https://img.shields.io/static/v1?style=for-the-badge&message=Cookiecutter&color=222222&logo=Cookiecutter&logoColor=D4AA00&label=)
![GitHub](https://img.shields.io/static/v1?style=for-the-badge&message=GitHub&color=181717&logo=GitHub&logoColor=FFFFFF&label=)

ℹ This template is intended to be used when following the contributing process for devcontainers-contrib/features. These directions are a duplicate of those in `CONTRIBUTING.md`.

1. Fork the devcontainers-contrib/features repository under your own GitHub account
2. Clone your new fork!
    ```bash
    git clone https://github.com/octocat/devcontainers-contrib-features.git 
    cd devcontainers-contrib-features
    ```
3. Run Cookiecutter on the `template/` folder while in the root of the repo
    ```bash
    cookiecutter template
    ```
4. Follow the onscreen prompts to add your new feature (TODO: Add image here)
5. Commit your changes with a descriptive message
    ```bash
    git add -A
    git commit -m "Added 'bikeshed' feature"
    ```
6. `git push` to your forked repository
    ```bash
    git push -u origin main
    ```
7. Open a new Pull Request against the devcontainers-contrib/features repo with your fork
8. Profit!

</details>

**Comment by jcbhmr** [comment]
I think is being addressed with the subpkg method instead of directly in this repository. Closing.

**Comment by danielbraun89** [comment]
Wow! First of all let me thank you for the effort you have put into this, and for the very detailed issues and PRs :smiley:  Very very much appreciated!

a common pattern with cookiecutter templates is to have them in their own repo, however since this template is so coupled to the features repo (with the "features/src" "features/test" file structure hierarchy) I agree it makes more sense to have it over there, and as you said - more user friendly , as also all the examples are in the same place.

so I merged your PR and from now on will continue to develop it in the pkgs subdir under the features repo

I guess I can now delete this repo will probably do it later this week after I make sure didnt forgot anything
